//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkTracker {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkTracker.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance was already submitted for this day. You wish to update the attendance ?.
        /// </summary>
        internal static string AttendanceSubmissionWarning {
            get {
                return ResourceManager.GetString("AttendanceSubmissionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Choose the date range to calculate the salary .
        /// </summary>
        internal static string ChooseDateRange {
            get {
                return ResourceManager.GetString("ChooseDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the date range..
        /// </summary>
        internal static string DateRangeSelectionWarning {
            get {
                return ResourceManager.GetString("DateRangeSelectionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job with this name already exists.
        /// </summary>
        internal static string DuplicateJobName {
            get {
                return ResourceManager.GetString("DuplicateJobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile number already exists.
        /// </summary>
        internal static string DuplicateMobileNumber {
            get {
                return ResourceManager.GetString("DuplicateMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add the worker, duplicate worker name.
        /// </summary>
        internal static string DuplicateWorkerName {
            get {
                return ResourceManager.GetString("DuplicateWorkerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a end date..
        /// </summary>
        internal static string EndDateError {
            get {
                return ResourceManager.GetString("EndDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to process the request..
        /// </summary>
        internal static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for {0}.
        /// </summary>
        internal static string InvalidValue {
            get {
                return ResourceManager.GetString("InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job has been added successfully.
        /// </summary>
        internal static string JobAddedSuccess {
            get {
                return ResourceManager.GetString("JobAddedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid Job name.
        /// </summary>
        internal static string JobNameError {
            get {
                return ResourceManager.GetString("JobNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login to continue.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to login..
        /// </summary>
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date should be greater than start date..
        /// </summary>
        internal static string NegativeDateRange {
            get {
                return ResourceManager.GetString("NegativeDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No job-assignment is found in this given date range..
        /// </summary>
        internal static string NoJobStatistics {
            get {
                return ResourceManager.GetString("NoJobStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP is not recognized.
        /// </summary>
        internal static string OtpMismatch {
            get {
                return ResourceManager.GetString("OtpMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password mismatch.
        /// </summary>
        internal static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered amount is invalid.
        /// </summary>
        internal static string PaymentAmountInvalidWarning {
            get {
                return ResourceManager.GetString("PaymentAmountInvalidWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select any one payment type..
        /// </summary>
        internal static string PaymentSelectionAtleastOneWarning {
            get {
                return ResourceManager.GetString("PaymentSelectionAtleastOneWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select only one payment type..
        /// </summary>
        internal static string PaymentSelectionOnlyOneWarning {
            get {
                return ResourceManager.GetString("PaymentSelectionOnlyOneWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the OTP sent to {0}.
        /// </summary>
        internal static string PleaseEnterOtp {
            get {
                return ResourceManager.GetString("PleaseEnterOtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration has been completed.
        /// </summary>
        internal static string RegistrationSuccess {
            get {
                return ResourceManager.GetString("RegistrationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a starting date..
        /// </summary>
        internal static string StartDateError {
            get {
                return ResourceManager.GetString("StartDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment is added successfully.
        /// </summary>
        internal static string SuccessfulPayment {
            get {
                return ResourceManager.GetString("SuccessfulPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been added successfully.
        /// </summary>
        internal static string UserAddedSuccess {
            get {
                return ResourceManager.GetString("UserAddedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username/Password mismatch..
        /// </summary>
        internal static string UsernamePasswordMismatch {
            get {
                return ResourceManager.GetString("UsernamePasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a worker..
        /// </summary>
        internal static string WorkerSelectionWarning {
            get {
                return ResourceManager.GetString("WorkerSelectionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
